/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.common.entities;

import javax.persistence.Entity;
import javax.persistence.Id;
import com.saburi.common.utils.CommonEnums.AccountTypes;
import javax.persistence.Enumerated;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ForeignKey;
import javax.persistence.OneToOne;

@Entity
public class AccountCategory extends DBEntity {

    @Column(name = "idHelper", updatable = false)
    private int idHelper;
    @Enumerated
    @Column(name = "accountType")
    private AccountTypes accountType;
    @Id
    @Column(name = "categoryID", updatable = false, length = 20, nullable = false)
    private String categoryID;
    @Column(name = "categoryName", length = 100, nullable = false)
    private String categoryName;
    @OneToOne
    @JoinColumn(name = "parentCategoryID", foreignKey = @ForeignKey(name = "fkParentCategoryIDAccountCategory"))
    private AccountCategory parentCategory;
    private boolean readOnly;
    private boolean hidden;

    public AccountCategory() {
    }

    public AccountCategory(int idHelper, AccountTypes accountType, String categoryID, String categoryName, AccountCategory parentCategory, boolean readOnly, boolean hidden) {
        this.idHelper = idHelper;
        this.accountType = accountType;
        this.categoryID = categoryID;
        this.categoryName = categoryName;
        this.parentCategory = parentCategory;
        this.readOnly = readOnly;
        this.hidden = hidden;

    }

    public int getIdHelper() {
        return idHelper;
    }

    public void setIdHelper(int idHelper) {
        this.idHelper = idHelper;
    }

    public AccountTypes getAccountType() {
        return accountType;
    }

    public void setAccountType(AccountTypes accountType) {
        this.accountType = accountType;
    }

    public String getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(String categoryID) {
        this.categoryID = categoryID;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public AccountCategory getParentCategory() {
        return parentCategory;
    }

    public void setParentCategory(AccountCategory parentCategory) {
        this.parentCategory = parentCategory;
    }

    public boolean isReadOnly() {
        return readOnly;
    }

    public void setReadOnly(boolean readOnly) {
        this.readOnly = readOnly;
    }

    public boolean isHidden() {
        return hidden;
    }

    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof AccountCategory)) {
            return false;
        }

        AccountCategory accountCategory = (AccountCategory) o;

        return this.getId().equals(accountCategory.getId());
    }

    @Override
    public int hashCode() {
        return this.categoryID.hashCode();

    }

    @Override
    public Object getId() {
        return this.categoryID;
    }

    @Override
    public String getDisplayKey() {
        return this.categoryName;
    }

}
