/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.common.entities;

import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ForeignKey;
import javax.persistence.Lob;
import javax.persistence.OneToOne;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

@Entity
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
public class AppUser extends DBEntity {

    @Id
    @Column(name = "loginID", updatable = false, length = 20, nullable = false)
    private String loginID;
    @Column(name = "firstName", length = 20, nullable = false)
    private String firstName;
    @Column(name = "lastName", length = 20, nullable = false)
    private String lastName;
    @Column(name = "staffNo", length = 20)
    private String staffNo;
    @Lob
    @Column(name = "password")
    private String password;
    @OneToOne
    @JoinColumn(name = "roleID", foreignKey = @ForeignKey(name = "fkRoleAppUser"))
    private UserRole role;

    public AppUser() {
    }

    public AppUser(String loginID, String firstName, String lastName, String staffNo, String password, UserRole role) {
        this.loginID = loginID;
        this.firstName = firstName;
        this.lastName = lastName;
        this.staffNo = staffNo;
        this.password = password;
        this.role = role;

    }

    public String getLoginID() {
        return loginID;
    }

    public void setLoginID(String loginID) {
        this.loginID = loginID;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getStaffNo() {
        return staffNo;
    }

    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserRole getRole() {
        return role;
    }

    public void setRole(UserRole role) {
        this.role = role;
    }

    @Override
    public Object getId() {
        return this.loginID;
    }

    @Override
    public String getDisplayKey() {
        return this.firstName + " " + this.lastName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof AppUser)) {
            return false;
        }

        AppUser appUser = (AppUser) o;

        return Objects.equals(this.getId(), appUser.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(this.loginID);

    }
    
    

}
