/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.common.entities;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;
import com.saburi.common.utils.CommonEnums.BusinessTypes;
import javax.persistence.Enumerated;
import javax.persistence.Lob;
import javax.validation.constraints.Size;

@Entity
public class Company extends DBEntity {

    @Column(name = "iDHelper", updatable = false)
    private int iDHelper;
    @Id
    @Column(name = "companyID", updatable = false, length = 20, nullable = false)
    private String companyID;
    @Column(name = "companyName", length = 100, unique = true, nullable = false)
    private String companyName;
    @Enumerated
    @Column(name = "businessType")
    private BusinessTypes businessType;
    @Column(name = "physicalAddress", length = 100)
   @Size(max = 100, message = "Length length for ${validatedValue} cannot be greater than 100")
    private String physicalAddress;
    @Column(name = "phone", length = 30)
    private String phone;
    @Column(name = "email", length = 100)
    private String email;
    @Column(name = "webSite", length = 100)
    private String webSite;
    @Column(name = "tagLine", length = 100)
    private String tagLine;
    @Lob
    private byte[] logo;

    public Company() {
    }

    public Company(int iDHelper, String companyID, String companyName, BusinessTypes businessType, String physicalAddress, String phone, String email, String webSite, String tagLine, byte[] logo) {
        this.iDHelper = iDHelper;
        this.companyID = companyID;
        this.companyName = companyName;
        this.businessType = businessType;
        this.physicalAddress = physicalAddress;
        this.phone = phone;
        this.email = email;
        this.webSite = webSite;
        this.tagLine = tagLine;
        this.logo = logo;

    }

    public int getIDHelper() {
        return iDHelper;
    }

    public void setIDHelper(int iDHelper) {
        this.iDHelper = iDHelper;
    }

    public String getCompanyID() {
        return companyID;
    }

    public void setCompanyID(String companyID) {
        this.companyID = companyID;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public BusinessTypes getBusinessType() {
        return businessType;
    }

    public void setBusinessType(BusinessTypes businessType) {
        this.businessType = businessType;
    }

    public String getPhysicalAddress() {
        return physicalAddress;
    }

    public void setPhysicalAddress(String physicalAddress) {
        this.physicalAddress = physicalAddress;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWebSite() {
        return webSite;
    }

    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }

    public String getTagLine() {
        return tagLine;
    }

    public void setTagLine(String tagLine) {
        this.tagLine = tagLine;
    }

    public byte[] getLogo() {
        return logo;
    }

    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Company)) {
            return false;
        }

        Company company = (Company) o;

        return this.getId().equals(company.getId());
    }

    @Override
    public int hashCode() {
        return this.companyID.hashCode();

    }

    @Override
    public Object getId() {
        return this.companyID;
    }

    @Override
    public String getDisplayKey() {
        return this.companyName;
    }

}
