/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.common.entities;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ForeignKey;
import javax.persistence.OneToOne;
import com.saburi.common.utils.SearchColumn.SearchDataTypes;
import javax.persistence.Enumerated;

@Entity
public class SearchColumn extends DBEntity {

    @Id
    @Column(name = "columnID", updatable = false, length = 100, nullable = false)
    private String columnID;
    @OneToOne
    @JoinColumn(name = "accessObjectID", foreignKey = @ForeignKey(name = "fkAccessObjectIDSearchColumn"), nullable = false)
    private AccessObject accessObject;
    @Column(name = "name", length = 100, nullable = false)
    private String name;
    @Column(name = "displayValue", length = 100)
    private String displayValue;
    private String columValue;
    @Enumerated
    @Column(name = "dataType")
    private SearchDataTypes dataType;
    private boolean hidden;

    public SearchColumn() {
    }

    public SearchColumn(String columnID, AccessObject accessObject, String name, String displayValue, String columnValue, SearchDataTypes dataType, boolean hidden) {
        this.columnID = columnID;
        this.accessObject = accessObject;
        this.name = name;
        this.displayValue = displayValue;
        this.columValue = columnValue;
        this.dataType = dataType;
        this.hidden = hidden;

    }

    public String getColumnID() {
        return columnID;
    }

    public void setColumnID(String columnID) {
        this.columnID = columnID;
    }

    public AccessObject getAccessObject() {
        return accessObject;
    }

    public void setAccessObject(AccessObject accessObject) {
        this.accessObject = accessObject;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDisplayValue() {
        return displayValue;
    }

    public void setDisplayValue(String displayValue) {
        this.displayValue = displayValue;
    }

    public Object getColumnValue() {
        return columValue;
    }

    public void setColumnValue(String value) {
        this.columValue = value;
    }

    public SearchDataTypes getDataType() {
        return dataType;
    }

    public void setDataType(SearchDataTypes dataType) {
        this.dataType = dataType;
    }

    public boolean isHidden() {
        return hidden;
    }

    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof SearchColumn)) {
            return false;
        }

        SearchColumn searchColumn = (SearchColumn) o;

        return this.getId().equals(searchColumn.getId());
    }

    @Override
    public int hashCode() {
        return this.columnID.hashCode();

    }

    @Override
    public Object getId() {
        return this.columnID;
    }

    @Override
    public String getDisplayKey() {
        return this.name;
    }

}
