/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.common.entities;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ForeignKey;
import javax.persistence.OneToOne;
import javax.persistence.Column;

@Entity
public class Village extends DBEntity {

    @Column(name = "idHelper", updatable = false)
    private int idHelper;
    @OneToOne
    @JoinColumn(name = "parishID", foreignKey = @ForeignKey(name = "fkParishIDVillage"), nullable = false)
    private Parish parish;
    @Id
    @Column(name = "villageID", updatable = false, length = 20, nullable = false)
    private String villageID;
    @Column(name = "villageName", length = 100)
    private String villageName;

    public Village() {
    }

    public Village(int idHelper, Parish parish, String villageID, String villageName) {
        this.idHelper = idHelper;
        this.parish = parish;
        this.villageID = villageID;
        this.villageName = villageName;

    }

    public int getIdHelper() {
        return idHelper;
    }

    public void setIdHelper(int idHelper) {
        this.idHelper = idHelper;
    }

    public Parish getParish() {
        return parish;
    }

    public void setParish(Parish parish) {
        this.parish = parish;
    }

    public String getVillageID() {
        return villageID;
    }

    public void setVillageID(String villageID) {
        this.villageID = villageID;
    }

    public String getVillageName() {
        return villageName;
    }

    public void setVillageName(String villageName) {
        this.villageName = villageName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Village)) {
            return false;
        }

        Village village = (Village) o;

        return this.getId().equals(village.getId());
    }

    @Override
    public int hashCode() {
        return this.villageID.hashCode();

    }

    @Override
    public Object getId() {
        return this.villageID;
    }

    @Override
    public String getDisplayKey() {
        return this.villageName;
    }

}
