/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.common.dbaccess;

import com.saburi.common.entities.SubCounty;
import javafx.beans.property.*;
import java.util.ArrayList;
import java.util.List;
import javafx.util.Pair;
import com.saburi.common.utils.SearchColumn;
import com.saburi.common.utils.SearchColumn.SearchDataTypes;
import com.saburi.common.entities.County;

public class SubCountyDA extends DBAccess {

    private SubCounty subCounty;
    private SimpleIntegerProperty idHelper = new SimpleIntegerProperty(this, "idHelper");
    private SimpleStringProperty countyDisplay = new SimpleStringProperty(this, "countyDisplay");
    private SimpleObjectProperty countyID = new SimpleObjectProperty(this, "countyID");
    private County county;
    private SimpleStringProperty subCountyID = new SimpleStringProperty(this, "subCountyID");
    private SimpleStringProperty subCountyName = new SimpleStringProperty(this, "subCountyName");

    public SubCountyDA() {
        createSearchColumns();
    }

    public SubCountyDA(String persistenceUnit) {
        super(persistenceUnit);
    }

    public SubCountyDA(SubCounty subCounty) {
        this.subCounty = subCounty;
        initialseProprties();
        createSearchColumns();
    }

    public SubCountyDA(String persistenceUnit, SubCounty subCounty) {
        super(persistenceUnit);
        this.subCounty = subCounty;
        initialseProprties();
        createSearchColumns();
    }

    public SubCountyDA(County county, String subCountyID, String subCountyName) {
        this.subCounty = new SubCounty(getNextIdHelper(county), county, subCountyID, subCountyName);
        initialseProprties();
        createSearchColumns();
    }

    public SubCountyDA(String persistenceUnit, County county, String subCountyID, String subCountyName) {
        this.subCounty = new SubCounty(getNextIdHelper(county), county, subCountyID, subCountyName);
        initialseProprties();
        createSearchColumns();
    }

    public int getIdHelper() {
        return idHelper.get();
    }

    public void setIdHelper(int idHelper) {
        subCounty.setIdHelper(idHelper);
        this.idHelper.set(idHelper);
    }

    public County getCounty() {
        return county;
    }

    public Object getCountyID() {
        return countyID.get();
    }

    public String getCountyDisplay() {
        return countyDisplay.get();
    }

    public CountyDA getCountyDA() {
        if (this.county == null) {
            return new CountyDA();
        } else {
            return new CountyDA(this.county);
        }
    }

    public Pair<String, Object> getCountyPair() {
        if (this.getCountyDA() == null) {
            return new Pair<>("", "");
        } else {
            return this.getCountyDA().keyValuePair();
        }
    }

    public void setCounty(County county) {
        subCounty.setCounty(county);
        this.county = county;
    }

    public String getSubCountyID() {
        return subCountyID.get();
    }

    public void setSubCountyID(String subCountyID) {
        subCounty.setSubCountyID(subCountyID);
        this.subCountyID.set(subCountyID);
    }

    public String getSubCountyName() {
        return subCountyName.get();
    }

    public void setSubCountyName(String subCountyName) {
        subCounty.setSubCountyName(subCountyName);
        this.subCountyName.set(subCountyName);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof SubCountyDA)) {
            return false;
        }

        SubCountyDA subCountyDA = (SubCountyDA) o;

        if (subCountyDA.getDBEntity() == null || this.getDBEntity() == null) {
            return false;
        }
        return this.getId().equals(subCountyDA.getId());
    }

    @Override
    public int hashCode() {
        return subCounty.getId().hashCode();
    }

    private void initialseProprties() {
        this.dBEntity = subCounty;
        this.idHelper = new SimpleIntegerProperty(subCounty.getIdHelper());
        this.county = subCounty.getCounty();
        this.countyID = new SimpleObjectProperty(county.getId());
        this.countyDisplay = new SimpleStringProperty(county.getDisplayKey());
        this.subCountyID = new SimpleStringProperty(subCounty.getSubCountyID());
        this.subCountyName = new SimpleStringProperty(subCounty.getSubCountyName());
        initCommonProprties();

    }

    private void createSearchColumns() {
        this.searchColumns.add(new SearchColumn("countyID", "County ID", this.countyID.get(), SearchDataTypes.STRING, SearchColumn.SearchType.Equal));
        this.searchColumns.add(new SearchColumn("countyDisplay", "County", this.countyDisplay.get(), SearchDataTypes.STRING));
        this.searchColumns.add(new SearchColumn("subCountyID", "Sub County ID", this.subCountyID.get(), SearchDataTypes.STRING));
        this.searchColumns.add(new SearchColumn("subCountyName", "Sub County Name", this.subCountyName.get(), SearchDataTypes.STRING));
        this.getSearchColumns().addAll(this.getDefaultSearchColumns());

    }

    @Override
    public List<SearchColumn> getSearchColumns() {
        return this.searchColumns;
    }

    @Override
    public Object getId() {
        return this.subCounty.getId();
    }

    @Override
    public String getDisplayKey() {
        return this.subCounty.getDisplayKey();
    }

    public static List<SubCountyDA> getSubCountyDAs(List<SubCounty> subCountys) {
        List<SubCountyDA> list = new ArrayList<>();
        subCountys.forEach((subCounty) -> {
            list.add(new SubCountyDA(subCounty));
        });
        return list;
    }

    public static List<SubCounty> getSubCountyList(List<SubCountyDA> subCountyDAs) {
        List<SubCounty> subCountys = new ArrayList<>();
        subCountyDAs.forEach(a -> subCountys.add(a.subCounty));
        return subCountys;
    }

    public boolean save() throws Exception {
        return super.persist(this.subCounty);

    }

    public boolean update() throws Exception {
        return super.merge(this.subCounty);

    }

    public boolean delete() {
        return super.remove(this.subCounty);

    }

    public SubCounty getSubCounty(String subCountyID) {
        return (SubCounty) super.find(SubCounty.class, subCountyID);
    }

    public List<SubCounty> getSubCountys() {
        return super.find(SubCounty.class);
    }

    @Override
    public List<DBAccess> get() {
        List<DBAccess> list = new ArrayList<>();
        selectQuery(SubCounty.class).forEach(o -> list.add(new SubCountyDA((SubCounty) o)));
        return list;
    }

    public SubCountyDA get(String subCountyID) throws Exception {
        SubCounty oSubCounty = (SubCounty) super.find(SubCounty.class, subCountyID);
        if (oSubCounty == null) {
            throw new Exception("No Record with id: " + subCountyID);
        }
        return new SubCountyDA(oSubCounty);
    }

    public List<SubCountyDA> get(String columName, Object value) {
        List<SubCounty> data = super.find(SubCounty.class, columName, value);
        List<SubCountyDA> list = new ArrayList<>();
        data.forEach(da -> list.add(new SubCountyDA(da)));
        return list;
    }

    public List<Pair<String, Object>> keyValuePairs() {
        List<Pair<String, Object>> pairs = new ArrayList<>();
        this.get().forEach((t) -> pairs.add(t.keyValuePair()));
        return pairs;
    }

    public List<Pair<String, Object>> keyValuePairs(String columName, Object value) {
        List<Pair<String, Object>> pairs = new ArrayList<>();
        this.get(columName, value).forEach((t) -> pairs.add(t.keyValuePair()));
        return pairs;
    }

    public int getMax(String columnName) {
        return super.getMax(SubCounty.class, columnName);
    }

    public int getMax(String columnName, String comparatorColumn, Object comparatorVaue) {
        return super.getMax(SubCounty.class, columnName, comparatorColumn, comparatorVaue);
    }

    public final int getNextIdHelper(Object county) {
        return this.getMax("idHelper", "county", county) + 1;
    }

    public String getNextSubCountyID(int idHelper, String county) {
        return new IDGeneratorDA().getToAppendString(SubCounty.class.getSimpleName(), county, idHelper);
    }

    public List<SubCounty> getSubCountys(String columName, Object value) {
        return super.find(SubCounty.class, columName, value);
    }

    public String getDistrictID() {
        return this.getCounty().getDistrict().getLookupDataID();
    }

    public String getDistrict() {
        return this.getCounty().getDistrict().getDisplayKey();
    }

}
