/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.common.controllers;

import java.net.URL;
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import static com.saburi.common.utils.FXUIUtils.*;
import com.saburi.common.utils.Utilities.FormMode;
import static com.saburi.common.utils.FXUIUtils.warningOk;
import com.saburi.common.dbaccess.ChartAccountDA;
import javafx.scene.control.TextField;
import javafx.scene.control.ComboBox;
import com.saburi.common.utils.CommonEnums.AccountTypes;
import javafx.collections.FXCollections;
import javafx.scene.control.MenuItem;
import com.saburi.common.dbaccess.AccountCategoryDA;
import com.saburi.common.entities.AccountCategory;
import com.saburi.common.utils.CommonEnums.AccountActions;
import com.saburi.common.utils.CommonEnums.AccountReports;
import com.saburi.common.utils.CommonNavigate;
import javafx.scene.control.CheckBox;

public class ChartAccountController extends EditController {

    private final ChartAccountDA oChartAccountDA = new ChartAccountDA();
    @FXML
    private ComboBox cboAccountType;
    @FXML
    private ComboBox cboCategory;
    @FXML
    private MenuItem cmiSelectCategory;
    @FXML
    private TextField txtAccountID;
    @FXML
    private TextField txtAccountName;
    @FXML
    private ComboBox cboAccountAction;
    @FXML
    private ComboBox cboAccountReport;
    @FXML
    private TextField txtOpeningBalance;
    @FXML
    private TextField txtClosingBalance;
    @FXML
    private CheckBox chkContra;
    @FXML
    private CheckBox chkReadOnly;
    @FXML
    private CheckBox chkControlAccount;
    @FXML
    private CheckBox chkHidden;
    private final AccountCategoryDA oAccountCategoryDA = new AccountCategoryDA();

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        try {
            cboAccountType.setItems(FXCollections.observableArrayList(AccountTypes.values()));
            loadDBEntities(new AccountCategoryDA().getAccountCategorys(), cboCategory);
            cboAccountAction.setItems(FXCollections.observableArrayList(AccountActions.values()));
            cboAccountReport.setItems(FXCollections.observableArrayList(AccountReports.values()));
            validateNumber(txtOpeningBalance);
            validateNumber(txtClosingBalance);
            this.primaryKeyControl = txtAccountID;
            this.dbAccess = oChartAccountDA;
            this.restrainColumnConstraint = false;
            this.minSize = 360;
            cboAccountType.setOnAction(e -> AccountTypeSelectected());
            cboCategory.setOnAction(e -> this.setNextAccountID());
            chkContra.setOnAction(e -> setDefaultSelections());

            selectItem(CommonNavigate.MAIN_CLASS,cmiSelectCategory, new AccountCategoryDA(), "View", "Category", 700, 400, cboCategory, true);
        } catch (Exception e) {
            errorMessage(e);
        } finally {
        }
    }

    @Override
    protected void save() {
        try {
            AccountTypes accountType = (AccountTypes) getSelectedValue(cboAccountType, "Account Type");
            AccountCategory category = (AccountCategory) getEntity(cboCategory, "Category No");
            String accountID = getText(txtAccountID, "Account ID");
            String accountName = getText(txtAccountName, "Account Name");
            AccountActions accountAction = (AccountActions) getSelectedValue(cboAccountAction, "Account Action");
            AccountReports accountReport = (AccountReports) getSelectedValue(cboAccountReport, "Account Report");
            double openingBalance = getDouble(txtOpeningBalance);
            double closingBalance = getDouble(txtClosingBalance);
            boolean contra = chkContra.isSelected();
            boolean readOnly = chkReadOnly.isSelected();
            boolean controlAccount = chkControlAccount.isSelected();
            boolean hidden = chkHidden.isSelected();

            ChartAccountDA chartAccountDA = new ChartAccountDA(accountType, category, accountID, accountName, accountAction, accountReport, openingBalance, closingBalance, contra, readOnly, controlAccount, hidden);
            String buttonText = btnSave.getText();
            if (buttonText.equalsIgnoreCase(FormMode.Save.name())) {
                chartAccountDA.save();
                message("Saved Successfully");
                clear();
            } else if (buttonText.equalsIgnoreCase(FormMode.Update.name())) {
                chartAccountDA.update();
                message("Updated Successfully");
            }
            this.dbAccess = chartAccountDA;
        } catch (Exception e) {
            errorMessage(e);
        } finally {
        }
    }

    @Override
    protected void delete() {
        try {
            String accountID = getText(txtAccountID, "Account ID");
            ChartAccountDA chartAccountDA = oChartAccountDA.get(accountID);
            if (!warningOk("Confirm Delete", "You are about to delete a record with ID: " + accountID + " Are you sure you want to continue?", "Remember this action cannot be un done")) {
                return;
            }
            if (chartAccountDA.delete()) {
                message("Deleted Successfully");
                this.clear();
            }
        } catch (Exception e) {
            errorMessage(e);
        }
    }

    @Override
    public void loadData() {
        try {
            String accountID = getText(txtAccountID, "Account ID");

            ChartAccountDA chartAccountDA = oChartAccountDA.get(accountID);
            cboAccountType.setValue(chartAccountDA.getAccountType());
            cboCategory.setValue(chartAccountDA.getCategory());
            txtAccountID.setText(chartAccountDA.getAccountID());
            txtAccountName.setText(chartAccountDA.getAccountName());
            cboAccountAction.setValue(chartAccountDA.getAccountAction());
            cboAccountReport.setValue(chartAccountDA.getAccountReport());
            txtOpeningBalance.setText(chartAccountDA.getOpeningBalanceDisplay());
            txtClosingBalance.setText(chartAccountDA.getClosingBalanceDisplay());
            chkContra.setSelected(chartAccountDA.isContra());
            chkReadOnly.setSelected(chartAccountDA.isReadOnly());
            chkControlAccount.setSelected(chartAccountDA.isControlAccount());
            chkHidden.setSelected(chartAccountDA.isHidden());

        } catch (Exception e) {
            errorMessage(e);
        }

    }

    private void setNextAccountID() {
        try {
            if (btnSave.getText().equalsIgnoreCase(FormMode.Save.name())) {
                AccountCategory category = (AccountCategory) getEntity(cboCategory);
                String categoryID = category != null ? category.getCategoryID() : "";
                txtAccountID.setText(oChartAccountDA.getNextAccountID(oChartAccountDA.getNextIdHelper(category), categoryID));
            }
        } catch (Exception e) {
            errorMessage(e);
        }
    }

    private void clear() {
        txtAccountID.clear();
        txtAccountName.clear();

        txtOpeningBalance.clear();
        txtClosingBalance.clear();
        chkContra.setSelected(false);
        chkReadOnly.setSelected(false);
        chkControlAccount.setSelected(false);
        chkHidden.setSelected(false);
        this.setNextAccountID();
    }

    private void setDefaultSelections() {
        AccountTypes accountType = (AccountTypes) cboAccountType.getValue();
        AccountActions defaultAccountAction = null;
        AccountReports defaultAccountReport = null;
        if (chkContra.isSelected()) {
            if (accountType.equals(AccountTypes.Asset) || accountType.equals(AccountTypes.Expense)) {
                defaultAccountAction = AccountActions.Credit;
                defaultAccountReport = AccountReports.Financial_Statement;
            } else if (accountType.equals(AccountTypes.Income) || accountType.equals(AccountTypes.Equity) || accountType.equals(AccountTypes.Liability)) {
                defaultAccountAction = AccountActions.Debit;
                defaultAccountReport = AccountReports.Balance_Sheet;
            }

        } else {

            if (accountType.equals(AccountTypes.Asset) || accountType.equals(AccountTypes.Expense)) {
                defaultAccountAction = AccountActions.Debit;
                defaultAccountReport = AccountReports.Balance_Sheet;
            } else if (accountType.equals(AccountTypes.Income) || accountType.equals(AccountTypes.Equity) || accountType.equals(AccountTypes.Liability)) {
                defaultAccountAction = AccountActions.Credit;
                defaultAccountReport = AccountReports.Financial_Statement;
            }

        }
        cboAccountAction.setValue(defaultAccountAction);
        cboAccountReport.setValue(defaultAccountReport);
    }

    private void AccountTypeSelectected() {
        AccountTypes accountType = (AccountTypes) cboAccountType.getValue();
        loadDBEntities(oAccountCategoryDA.getAccountCategoriesByAccountType(accountType), cboCategory);
        setDefaultSelections();

    }
}
