/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.common.controllers;

import java.net.URL;
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import static com.saburi.common.utils.FXUIUtils.*;
import com.saburi.common.utils.Utilities.FormMode;
import static com.saburi.common.utils.FXUIUtils.warningOk;
import com.saburi.common.dbaccess.ParishDA;
import javafx.scene.control.TextField;
import javafx.scene.control.ComboBox;
import javafx.scene.control.MenuItem;
import com.saburi.common.dbaccess.SubCountyDA;
import com.saburi.common.entities.SubCounty;
import com.saburi.common.utils.CommonNavigate;

public class ParishController extends EditController {

    private final ParishDA oParishDA = new ParishDA();
    @FXML
    private ComboBox cboSubCounty;
    @FXML
    private MenuItem cmiSelectSubCounty;
    @FXML
    private TextField txtParishID;
    @FXML
    private TextField txtParishName;

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        try {
//            this.minSize = 360;
            loadDBEntities(new SubCountyDA().getSubCountys(), cboSubCounty);

            this.primaryKeyControl = txtParishID;
            this.dbAccess = oParishDA;
            this.restrainColumnConstraint = false;
            this.popuprestrainConstraint = false;

            cboSubCounty.setOnAction(e -> this.setNextParishID());
            selectItem(CommonNavigate.MAIN_CLASS, cmiSelectSubCounty, new SubCountyDA(), "SubCounty", "Sub County", 400, 450, cboSubCounty, false);

        } catch (Exception e) {
            errorMessage(e);
        } finally {
        }
    }

    @Override
    protected void save() {
        try {
            this.editSuccessful = false;
            SubCounty subCounty = (SubCounty) getEntity(cboSubCounty, "Sub County");
            String parishID = getText(txtParishID, "Parish ID");
            String parishName = getText(txtParishName, "Parish Name");

            ParishDA parishDA = new ParishDA(subCounty, parishID, parishName);
            String buttonText = btnSave.getText();
            if (buttonText.equalsIgnoreCase(FormMode.Save.name())) {
                parishDA.save();
                message("Saved Successfully");
                clear();
            } else if (buttonText.equalsIgnoreCase(FormMode.Update.name())) {
                parishDA.update();
                message("Updated Successfully");
            }
            this.dbAccess = parishDA;
            this.editSuccessful = true;
        } catch (Exception e) {
            errorMessage(e);
        } finally {
        }
    }

    @Override
    protected void delete() {
        try {
            String parishID = getText(txtParishID, "Parish ID");
            ParishDA parishDA = oParishDA.get(parishID);
            if (!warningOk("Confirm Delete", "You are about to delete a record with ID: " + parishID + " Are you sure you want to continue?", "Remember this action cannot be un done")) {
                return;
            }
            if (parishDA.delete()) {
                message("Deleted Successfully");
                this.clear();
            }
        } catch (Exception e) {
            errorMessage(e);
        }
    }

    @Override
    public void loadData() {
        try {
            String parishID = getText(txtParishID, "Parish ID");

            ParishDA parishDA = oParishDA.get(parishID);
            cboSubCounty.setValue(parishDA.getSubCountyDA());
            txtParishID.setText(parishDA.getParishID());
            txtParishName.setText(parishDA.getParishName());

        } catch (Exception e) {
            errorMessage(e);
        }

    }

    private void setNextParishID() {
        try {
            if (btnSave.getText().equalsIgnoreCase(FormMode.Save.name())) {

                SubCounty subCounty = (SubCounty) getEntity(cboSubCounty);
                String subCountyID = subCounty == null ? "" : subCounty.getSubCountyID();
                txtParishID.setText(oParishDA.getNextParishID(oParishDA.getNextIdHelper(subCounty), subCountyID));
            }
        } catch (Exception e) {
            errorMessage(e);
        }
    }

   
}
